create table ACT_HI_TASKINST (
    ID_ VARCHAR2(128) not null,
    REV_ INTEGER default 1,
    PROC_DEF_ID_ VARCHAR2(128),
    TASK_DEF_ID_ VARCHAR2(128),
    TASK_DEF_KEY_ VARCHAR(510),
    PROC_INST_ID_ VARCHAR2(128),
    EXECUTION_ID_ VARCHAR2(128),
    SCOPE_ID_ VARCHAR(510),
    SUB_SCOPE_ID_ VARCHAR(510),
    SCOPE_TYPE_ VARCHAR(510),
    SCOPE_DEFINITION_ID_ VARCHAR(510),
    PROPAGATED_STAGE_INST_ID_ VARCHAR(510),
    PARENT_TASK_ID_ VARCHAR2(128),
    NAME_ VARCHAR(510),
    DESCRIPTION_ NVARCHAR2(2000),
    OWNER_ VARCHAR(510),
    ASSIGNEE_ VARCHAR(510),
    START_TIME_ TIMESTAMP(6) not null,
    CLAIM_TIME_ TIMESTAMP(6),
    END_TIME_ TIMESTAMP(6),
    DURATION_ NUMBER(19,0),
    DELETE_REASON_ NVARCHAR2(2000),
    PRIORITY_ INTEGER,
    DUE_DATE_ TIMESTAMP(6),
    FORM_KEY_ VARCHAR(510),
    CATEGORY_ VARCHAR(510),
    TENANT_ID_ VARCHAR(510) default '',
    LAST_UPDATED_TIME_ TIMESTAMP(6),
    primary key (ID_)
);

create table ACT_HI_TSK_LOG (
    ID_ NUMBER(19),
    TYPE_ VARCHAR2(128),
    TASK_ID_ VARCHAR2(128) not null,
    TIME_STAMP_ TIMESTAMP(6) not null,
    USER_ID_ VARCHAR(510),
    DATA_ NVARCHAR2(2000),
    EXECUTION_ID_ VARCHAR2(128),
    PROC_INST_ID_ VARCHAR2(128),
    PROC_DEF_ID_ VARCHAR2(128),
    SCOPE_ID_ VARCHAR(510),
    SCOPE_DEFINITION_ID_ VARCHAR(510),
    SUB_SCOPE_ID_ VARCHAR(510),
    SCOPE_TYPE_ VARCHAR(510),
    TENANT_ID_ VARCHAR(510) default '',
    primary key (ID_)
);

create sequence act_hi_task_evt_log_seq start with 1 increment by 1;

create index ACT_IDX_HI_TASK_SCOPE on ACT_HI_TASKINST(SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_TASK_SUB_SCOPE on ACT_HI_TASKINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_TASK_SCOPE_DEF on ACT_HI_TASKINST(SCOPE_DEFINITION_ID_, SCOPE_TYPE_);
