create table ACT_HI_VARINST (
    ID_ VARCHAR2(64) not null,
    REV_ INTEGER default 1,
    PROC_INST_ID_ VARCHAR2(64),
    EXECUTION_ID_ VARCHAR2(64),
    TASK_ID_ VARCHAR2(64),
    NAME_ VARCHAR2(255) not null,
    VAR_TYPE_ VARCHAR2(100),
    SCOPE_ID_ VARCHAR2(255),
    SUB_SCOPE_ID_ VARCHAR2(255),
    SCOPE_TYPE_ VARCHAR2(255),
    BYTEARRAY_ID_ VARCHAR2(64),
    DOUBLE_ NUMBER(38,10),
    LONG_ NUMBER(19,0),
    TEXT_ VARCHAR2(2000),
    TEXT2_ VARCHAR2(2000),
    CREATE_TIME_ TIMESTAMP(6),
    LAST_UPDATED_TIME_ TIMESTAMP(6),
    primary key (ID_)
);

create index ACT_IDX_HI_PROCVAR_NAME_TYPE on ACT_HI_VARINST(NAME_, VAR_TYPE_);
create index ACT_IDX_HI_VAR_SCOPE_ID_TYPE on ACT_HI_VARINST(SCOPE_ID_, SCOPE_TYPE_);
create index ACT_IDX_HI_VAR_SUB_ID_TYPE on ACT_HI_VARINST(SUB_SCOPE_ID_, SCOPE_TYPE_);
